### ISSUE TITLE
Installation instructions do not seem to include installation instructtions

### ISSUE THREAD

**Issue by kurtflint** [torbjon/newrelic_memory_agent#1]
Imagine you have never used Ruby. You use C and Python. But you want to use this plugin with your Nginx server and New Relic. I can't figure where to put it, how forking and installing someone else's project (who makes the same sort of instructions as here) and running it will install your program, etc. Is Ruby secure? Should I set up a minimum privileges account to own the Ruby apps, including this mysterious bundler?

Thanks, and I look forward to trying out your plugin if I get it figured out,

Kurt

**Comment by FabianKoestring** [comment]
:+1: 
Iam new to ruby and i dont know how to install this plugin.

**Comment by kurtflint** [comment]
Well, I've been writing for a good thirty years, and I'm getting a little grumpy (us old men, ie, over 40 are prone to get that way I'm told. When I was younger I thought it was because the old programmers slow down and can't compete with they young brilliant ones - now I know it is because they give us all of the spreadsheets and make us watch the "brilliant" kids while still writing our share :P )

Seriously though, I'm noting a trend where toward the beginning of a readme.md the perfectly brilliant author just skips past all preliminaries by pulling off this "set up as usual of course" instruction out of thin air. Back when there were only 3 or 4 things you would be expecting to see running on a computer at once (basic, cobol, pascal, ada when I went to school if I recall)(and yes, I still have punch cards to prove it) nobody would have been so bad about instructions for loading and running their stacks (a grad student often ran your stuff for you and you picked it up in the morning). 

I don't really want to learn Ruby just to get stats on my servers. Though it is kind of useful for writing VOIP control scripts.
